### ISSUE TITLE
Проблема с чтением из ClickHouse в многопотоке

### ISSUE THREAD

**Issue by Anwert** [ClickHouse/clickhouse-odbc#291]
Всем привет, у нас приложение на .net core, ходим в CH через odbc. Появилась проблема: когда несколько потоков одновременно пытаются прочитать данные из CH, приложение периодически падает с `AccessViolationException` https://docs.microsoft.com/en-us/dotnet/api/system.accessviolationexception?view=netframework-4.8. Исключение падало: 
- при вызове `Dispose()` у `OdbcConnection` или `OdbcCommand`::
```
at Interop+Odbc.SQLFreeHandle(SQL_HANDLE, IntPtr)
at Interop+Odbc.SQLFreeHandle(SQL_HANDLE, IntPtr)
at System.Data.Odbc.OdbcHandle.ReleaseHandle()
at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
at System.Data.Odbc.CMDWrapper.DisposeStatementHandle()
at System.Data.Odbc.CMDWrapper.Dispose()
at System.Data.Odbc.OdbcCommand.CloseCommandWrapper()
at System.Data.Odbc.OdbcCommand.DisconnectFromDataReaderAndConnection()
at System.Data.Odbc.OdbcCommand.Dispose(Boolean)
at System.Data.Common.DbCommand.DisposeAsync()
```
- при вызове `OdbcCommand.ExecuteReader`:
```
at Interop+Odbc.SQLAllocHandle(SQL_HANDLE, System.Data.Odbc.OdbcHandle, IntPtr ByRef)
at Interop+Odbc.SQLAllocHandle(SQL_HANDLE, System.Data.Odbc.OdbcHandle, IntPtr ByRef)
at Interop+Odbc.SQLAllocHandle(SQL_HANDLE, System.Data.Odbc.OdbcHandle, IntPtr ByRef)
at Interop+Odbc.SQLAllocHandle(SQL_HANDLE, System.Data.Odbc.OdbcHandle, IntPtr ByRef)
at System.Data.Odbc.OdbcHandle..ctor(SQL_HANDLE, System.Data.Odbc.OdbcHandle)
at System.Data.Odbc.OdbcHandle..ctor(SQL_HANDLE, System.Data.Odbc.OdbcHandle)
at System.Data.Odbc.OdbcCommand.GetStatementHandle()
at System.Data.Odbc.OdbcCommand.GetStatementHandle()
at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(System.Data.CommandBehavior, System.String, Boolean, System.Object[], SQL_API)
at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(System.Data.CommandBehavior, System.String, Boolean, System.Object[], SQL_API)
at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(System.Data.CommandBehavior, System.String, Boolean)
at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(System.Data.CommandBehavior, System.String, Boolean)
at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(System.Data.CommandBehavior, System.Threading.CancellationToken)
at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(System.Data.CommandBehavior, System.Threading.CancellationToken)
at System.Data.Common.DbCommand.ExecuteReaderAsync()
at System.Data.Common.DbCommand.ExecuteReaderAsync()
```

Проверял на версиях CH 19.17.9.60 и 20.1.8.41.

При этом если в несколько потоков делать запросы без чтения (к примеру, `insert..`), то все ок. У каждого потока свои инстансы OdbcConnection, OdbcCommand и OdbcReader (т.е. нет обращения к какой-то сущности odbc из нескольких потоков), проблема воспроизводится на версиях драйвера начиная с 1.1.1.20191108, на версии 1.1.0.20191028 этой проблемы не было. Если производить чтение в одном потоке или повесить лок на вызов `ExecuteReader()`, то тоже все ок. Проблема проявлялась и при использовании CH, запущенном в докере на windows и при использовании CH, запущенном на CentOS7 без докера.

Подскажите, пожалуйста, в чем может быть причина такого поведения?

**Comment by traceon** [comment]
Драйвер не поддерживает параллельное использование на данный момент. Сериализуйте вызов функций.

**Comment by Anwert** [comment]
Понял, спасибо.

**Comment by filimonov** [comment]
> Драйвер не поддерживает параллельное использование на данный момент. Сериализуйте вызов функций.

Кажется спецификация требует чтобы драйверы были thread-safe.

МБ стоит сделать в минимальном варианте - с доками, по типу https://docs.microsoft.com/en-us/sql/odbc/microsoft/thread-safety-notes-on-api-functions-odbc-driver-for-oracle?view=sql-server-ver15 ?

**Comment by traceon** [comment]
@filimonov откроешь issue для этого?

**Comment by hohaftf** [comment]
Проясните, пожалуйста, несколько моментов

Как поведут себя 2 параллельных SELECT при реализации thread-safe?
И вот это
> проблема воспроизводится на версиях драйвера начиная с 1.1.1.20191108, на версии 1.1.0.20191028 этой проблемы не было

**Comment by traceon** [comment]
Драйвер не был reentrant никогда, не воспроизводилось по случайности на том коде.

> Как поведут себя 2 параллельных SELECT при реализации thread-safe?

Трудно говорить точно сейчас, пока нет четкого плана реализации. Но скорее всего это будет 1 active statement per 1 connection. Т.е. для 2-х параллельных SELECT нужно будет иметь 2 Connection по одному отдельному Statement на каждом из них, и запускать каждый SELECT на своем Statement.
